micronaut:
  server:
    port: 8086
    cors:
      enabled: true
    #port: -1 --> para que el puerto sea aleatorio
  application:
    name: helloWork
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
    versioning:
      enabled: true
      default-version: 1
      header:
        enabled: true
        #names:
         # - 'X-API-VERSION'
  ssl:
    enabled: true
    buildSelfSigned: true # Micronaut creará un certificado autofirmado.
    port: 8080

hello:
  message:
    greetings:
      default: Hello
